### ISSUE TITLE
Formulate API Routes

### ISSUE THREAD

**Issue by DylanHalstead** [Sync-Space-49/syncspace-server#1]
Before writing the backend, we should formulate routes that the frontend will need to send requests to. Make a comprehensive list of route (api/:userid, api/:orgId/:boardId, etc) to figure out the scope and how to plan out each item

**Comment by Nathan-Laney** [comment]
# Routes

## Login
GET: fetch login site
POST: attempt to log in 

## Homepage
GET: fetch home page

**Comment by DylanHalstead** [comment]
- GET api/users/:userId
- POST api/users
  - username
  - email
  - password
  - pfp (optional)
- PUT api/users
  - username (optional)
  - email (optional)
  - password (optional)
  - pfp (optional)
- GET api/

**Comment by DylanHalstead** [comment]
@Nathan-Laney for boards and memebers for example I have it set so that the organizations id needs to be put into the request but could see how that's repetitive. Should we just check on the backend if the user is a part of the organization or should we have that + the explicit organizaitonId in the request. Leaning towards less in the route itself than the validation is done black box style

**Comment by DylanHalstead** [comment]
Realizing now that for this system to work we are likely going to need to send a JWT (JSON Web Token) with a lot of these requests so I put on the [scrumgenda](https://docs.google.com/document/d/19Gpqzcy3R9_40z6i6QQw9zq-zcQGdb51-4Nj80ubZCA/edit) we should talk about if that's something we are agreeance in using before going too deep

**Comment by DylanHalstead** [comment]
@Nathan-Laney Updated list if you wanna give it a run down. Not sure if it's exhaustive but is a majority for sure
