### ISSUE TITLE
[SPIKE] Investigate DB Implementation

### ISSUE THREAD

**Issue by DylanHalstead** [Sync-Space-49/syncspace-server#2]
We need to get a good idea how to set up the data in our system so we can plan out how to manipulate the data on [syncspace-server](https://github.com/Sync-Space-49/syncspace-server). Some work has been done creating an [ERD](https://lucid.app/lucidchart/ca6c8c8b-a2a3-4f4a-832b-9adc4bf87422/edit?viewport_loc=-14%2C4%2C2916%2C1628%2C0_0&invitationId=inv_198351b6-fa72-4bf0-a94d-93e06635a3cb) but it needs a bit of work and some finalization.

**Comment by Nathan-Laney** [comment]
https://cdn.discordapp.com/attachments/1148625755102773321/1149416037733904414/SyncSpace_Entity_Relationship_Diagram.png

**Comment by DylanHalstead** [comment]
[SyncSpace Entity Relationship Diagram.pdf](https://github.com/Sync-Space-49/syncspace-server/files/12589117/SyncSpace.Entity.Relationship.Diagram.pdf)

New ERD just dropped

**Comment by Nathan-Laney** [comment]
Determined for our usecase, docker containerized Postgres SQL instance was what we would go with. Also determined that hosting elsewhere is too expensive on cloud platforms, so we will locally host DB
