### ISSUE TITLE
[SPIKE] Set up CI/CD using Google Cloud

### ISSUE THREAD

**Issue by Nathan-Laney** [Sync-Space-49/syncspace-server#27]
Considered "SPIKE" because this will require research and will result in the creation of more tickets rather than a pull request

End goal: Auto spin up containers publicly accessible for VPN users for dev. Auto spin up releases for public internet

**Comment by Nathan-Laney** [comment]
Update: Blocked until I can determine why I am receiving fake connection issues with the google cloud instance

**Comment by Nathan-Laney** [comment]
I have a plan
Whitelist Cloud containers so that their IPs can access the DB from outside the VPN. Then remove tailscale setup from dockerfile
This would be good because I could use a sep database for prod very easily

OR 

Use a publicly available free or cheap database

**Comment by DylanHalstead** [comment]
Closed with #102
