### ISSUE TITLE
Create DB Tables

### ISSUE THREAD

**Issue by DylanHalstead** [Sync-Space-49/syncspace-server#6]
Based on the ERD from #2, create the actual DB tables in the language we choose

**Comment by DylanHalstead** [comment]
Postgres bc easy to get a free server

**Comment by Nathan-Laney** [comment]
can host myself if you want

**Comment by Nathan-Laney** [comment]
Resolved in PR https://github.com/Sync-Space-49/syncspace-server/pull/8
